### ISSUE TITLE
Adapter not compatible with js-controller 5

### ISSUE THREAD

**Issue by mcm1957** [pixcept/ioBroker.plenticore#84]
According to this issue at forum.iobroker.net

https://forum.iobroker.net/topic/68313/plenticore-adapter-startet-nicht-nach-aktualisierung

this adapter does not work with js-controller 5.

Neither release 2.2.0 nor 2.3.0 work according to original poster.

**Please verify your adapter with js-controller 5 and fix any problems detected.**

**Comment by elo79** [comment]
Unfortunately this didn´t fix the issue.
If I create the folders manually the adapter works for a few days and then the folders are gone again.
`
plenticore.0 | 2023-10-03 18:52:18.100 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
plenticore.0 | 2023-10-03 18:52:17.105 | error | Exception-Code: ERR_INVALID_ARG_TYPE: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
plenticore.0 | 2023-10-03 18:52:17.104 | error | TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined at Object.openSync (node:fs:582:10) at Object.writeFileSync (node:fs:2202:35) at Object.unload (/opt/iobroker/node_modules/iobroker.plenticore/lib/plenticore.js:839:5) at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.plenticore/main.js:40:14) at AdapterClass.emit (node:events:513:28) at AdapterClass._stop (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:1369:26) at AdapterClass._exceptionHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9113:18) at processTicksAndRejections (node:internal/process/task_queues:96:5)
plenticore.0 | 2023-10-03 18:52:17.100 | error | unhandled promise rejection: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
plenticore.0 | 2023-10-03 18:52:17.099 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
plenticore.0 | 2023-10-03 18:52:17.086 | error | Exception-Code: ENOENT: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0'
plenticore.0 | 2023-10-03 18:52:17.085 | error | Error: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0' at Object.mkdirSync (node:fs:1382:3) at Object.setup (/opt/iobroker/node_modules/iobroker.plenticore/lib/plenticore.js:761:6) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.plenticore/main.js:189:17) at processImmediate (node:internal/timers:468:21)
plenticore.0 | 2023-10-03 18:52:17.082 | error | uncaught exception: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/plenticore.0'
`

**Comment by mcm1957** [comment]
@elo79 
Just notices your last statements.
**I suggest to contact @Apollon77 for aid what to adapt for js-controller 5 for you special situation**.

In addition I would invite you to join our developer channel at telegrasm (or the linked discord channel) where several developers may assist you:

https://t.me/ioBroker_development (deutsch / german)
https://t.me/+gsX-e8k4mLtmZjZk (english)
https://t.me/+gsX-e8k4mLtmZjZk (deutsch, starters channel)

In addition I suggest to close PR https://github.com/ioBroker/ioBroker.repositories/pull/2657 as an update of the stable version does not make much sense while teh adapter is not functional at js-controller 5. Please let me now if this understanding is incorrect.

**Comment by Apollon77** [comment]
upgrade adapter-core dep and try

**Comment by pixcept** [comment]
Please check if updating to the latest git version solves it.

**Comment by IOGogo** [comment]
Nachdem ich meine Containerversion von V8 latest auf V9 latest aktualisiert habe läuft der Adapter auch mit der Version 2.2.0 mit js.controller 5.0.12 ohne Probleme auf meiner Synology Docker. Für mich stellt sich die Frage warum nicht unter V8 latest ?

**Comment by pixcept** [comment]
Darauf habe ich leider keine Antwort.

**Comment by mcm1957** [comment]
Ok, dann kann man ja schließen
