### ISSUE TITLE
bekomme warnung im Protokoll von ioborker

### ISSUE THREAD

**Issue by spidermike-74** [pixcept/ioBroker.plenticore#91]
![protokoll plenticore](https://github.com/pixcept/ioBroker.plenticore/assets/79029052/09965c84-5252-4195-9512-c3f923af0f02)

**Comment by schoemi** [comment]
Das liegt daran, dass der Adapter nicht mit dem JavaScript Adapter > 5.0 funktioniert.
Siehe hier: https://github.com/pixcept/ioBroker.plenticore/issues/90

**Comment by pixcept** [comment]
Please check if the latest git version fixes it.

**Comment by pixcept** [comment]
No further messages, so closing this. Please report back in case it still exists.
